import moment from "moment";
import type { BadgeVariant } from "../../components/elements";

export type MilestoneState =
  | "Completed"
  | "In Progress"
  | "Planned"
  | "Delayed"
  | "Cancelled";

export type MilestoneType = "Construction" | "Handover" | "Approval";

export interface PortfolioMilestone {
  id: string;
  name: string;
  project: string;
  projectCode: string;
  projectId: number;
  location: string;
  phase: string;
  owner: string;
  start: string;
  end: string;
  status: MilestoneState;
  critical: boolean;
  milestoneType: MilestoneType;
  dependsOn?: string;
}

export const milestoneStateVariant: Record<MilestoneState, BadgeVariant> = {
  Completed: "success",
  "In Progress": "info",
  Planned: "neutral",
  Delayed: "danger",
  Cancelled: "warning",
};

export const milestoneTypeOptions = [
  { label: "All types", value: "all" },
  { label: "Construction", value: "Construction" },
  { label: "Handover", value: "Handover" },
  { label: "Approval", value: "Approval" },
];

export const milestones: PortfolioMilestone[] = [
  {
    id: "M-01",
    name: "Architectural design approval",
    project: "Emerald Gardens Estate",
    projectCode: "DEV-001",
    projectId: 1,
    location: "GRA Phase 2, Port Harcourt",
    phase: "Site Preparation",
    owner: "Amara Bello",
    start: "2025-10-01",
    end: "2025-11-15",
    status: "Completed",
    critical: true,
    milestoneType: "Approval",
  },
  {
    id: "M-02",
    name: "Block A — weathertight",
    project: "Emerald Gardens Estate",
    projectCode: "DEV-001",
    projectId: 1,
    location: "GRA Phase 2, Port Harcourt",
    phase: "Structural Development",
    owner: "Tunde Okafor",
    start: "2025-11-16",
    end: "2026-03-30",
    status: "Completed",
    critical: true,
    milestoneType: "Construction",
    dependsOn: "Architectural design approval",
  },
  {
    id: "M-03",
    name: "Block B — finishing works",
    project: "Emerald Gardens Estate",
    projectCode: "DEV-001",
    projectId: 1,
    location: "GRA Phase 2, Port Harcourt",
    phase: "Finishing Stage",
    owner: "Tunde Okafor",
    start: "2026-04-01",
    end: "2026-07-20",
    status: "In Progress",
    critical: true,
    milestoneType: "Construction",
    dependsOn: "Block A — weathertight",
  },
  {
    id: "M-04",
    name: "Block A — Phase 1 handover",
    project: "Emerald Gardens Estate",
    projectCode: "DEV-001",
    projectId: 1,
    location: "GRA Phase 2, Port Harcourt",
    phase: "Handover Preparation",
    owner: "Amara Bello",
    start: "2026-07-21",
    end: "2026-06-24",
    status: "In Progress",
    critical: true,
    milestoneType: "Handover",
    dependsOn: "Block B — finishing works",
  },
  {
    id: "M-05",
    name: "Land acquisition close",
    project: "Greenfield Housing Scheme",
    projectCode: "DEV-002",
    projectId: 2,
    location: "Obio-Akpor, Port Harcourt",
    phase: "Site Preparation",
    owner: "Tunde Okafor",
    start: "2025-08-01",
    end: "2025-09-10",
    status: "Completed",
    critical: true,
    milestoneType: "Approval",
  },
  {
    id: "M-06",
    name: "Site preparation complete",
    project: "Greenfield Housing Scheme",
    projectCode: "DEV-002",
    projectId: 2,
    location: "Obio-Akpor, Port Harcourt",
    phase: "Site Preparation",
    owner: "Tunde Okafor",
    start: "2025-09-11",
    end: "2026-04-01",
    status: "Delayed",
    critical: true,
    milestoneType: "Construction",
    dependsOn: "Land acquisition close",
  },
  {
    id: "M-07",
    name: "Foundation works — Block 1",
    project: "Greenfield Housing Scheme",
    projectCode: "DEV-002",
    projectId: 2,
    location: "Obio-Akpor, Port Harcourt",
    phase: "Foundation Stage",
    owner: "Grace Eze",
    start: "2026-04-02",
    end: "2026-06-20",
    status: "Planned",
    critical: true,
    milestoneType: "Construction",
    dependsOn: "Site preparation complete",
  },
  {
    id: "M-08",
    name: "Planning & environmental approval",
    project: "Atlantic View Residences",
    projectCode: "DEV-003",
    projectId: 3,
    location: "Trans Amadi, Port Harcourt",
    phase: "Site Preparation",
    owner: "Stephen Okoro",
    start: "2025-11-01",
    end: "2025-12-15",
    status: "Completed",
    critical: true,
    milestoneType: "Approval",
  },
  {
    id: "M-09",
    name: "Tower B — foundation complete",
    project: "Atlantic View Residences",
    projectCode: "DEV-003",
    projectId: 3,
    location: "Trans Amadi, Port Harcourt",
    phase: "Foundation Stage",
    owner: "Bola Adisa",
    start: "2025-12-16",
    end: "2026-06-30",
    status: "Delayed",
    critical: true,
    milestoneType: "Construction",
    dependsOn: "Planning & environmental approval",
  },
  {
    id: "M-10",
    name: "Tower B — roofing stage",
    project: "Atlantic View Residences",
    projectCode: "DEV-003",
    projectId: 3,
    location: "Trans Amadi, Port Harcourt",
    phase: "Roofing Stage",
    owner: "Bola Adisa",
    start: "2026-07-01",
    end: "2026-10-15",
    status: "Planned",
    critical: true,
    milestoneType: "Construction",
    dependsOn: "Tower B — foundation complete",
  },
  {
    id: "M-11",
    name: "Foundation complete — Tower A",
    project: "Riverside Commercial Complex",
    projectCode: "DEV-004",
    projectId: 4,
    location: "Woji, Port Harcourt",
    phase: "Foundation Stage",
    owner: "Lola Adeyemi",
    start: "2025-09-15",
    end: "2025-12-01",
    status: "Completed",
    critical: false,
    milestoneType: "Construction",
  },
  {
    id: "M-12",
    name: "Level 10 slab pour",
    project: "Riverside Commercial Complex",
    projectCode: "DEV-004",
    projectId: 4,
    location: "Woji, Port Harcourt",
    phase: "Structural Development",
    owner: "Yusuf Idris",
    start: "2025-12-02",
    end: "2026-06-15",
    status: "In Progress",
    critical: false,
    milestoneType: "Construction",
    dependsOn: "Foundation complete — Tower A",
  },
  {
    id: "M-13",
    name: "Block D — weathertight",
    project: "Woji Estate Extension",
    projectCode: "DEV-005",
    projectId: 5,
    location: "Woji, Port Harcourt",
    phase: "Finishing Stage",
    owner: "Maria Santos",
    start: "2026-01-05",
    end: "2026-02-10",
    status: "Completed",
    critical: false,
    milestoneType: "Construction",
  },
  {
    id: "M-14",
    name: "Phase 2 estate handover",
    project: "Woji Estate Extension",
    projectCode: "DEV-005",
    projectId: 5,
    location: "Woji, Port Harcourt",
    phase: "Handover Preparation",
    owner: "Maria Santos",
    start: "2026-06-01",
    end: "2026-08-30",
    status: "Planned",
    critical: true,
    milestoneType: "Handover",
    dependsOn: "Block D — internal finishes",
  },
  {
    id: "M-15",
    name: "Block D — internal finishes",
    project: "Woji Estate Extension",
    projectCode: "DEV-005",
    projectId: 5,
    location: "Woji, Port Harcourt",
    phase: "Finishing Stage",
    owner: "Chen Wei",
    start: "2026-02-11",
    end: "2026-05-30",
    status: "In Progress",
    critical: false,
    milestoneType: "Construction",
    dependsOn: "Block D — weathertight",
  },
  {
    id: "M-16",
    name: "Substructure complete",
    project: "Royal Crest Apartments",
    projectCode: "DEV-006",
    projectId: 6,
    location: "Ada George, Port Harcourt",
    phase: "Foundation Stage",
    owner: "Daniel Ajayi",
    start: "2026-03-01",
    end: "2026-04-30",
    status: "Completed",
    critical: true,
    milestoneType: "Construction",
  },
  {
    id: "M-17",
    name: "Retail wing fit-out",
    project: "Royal Crest Apartments",
    projectCode: "DEV-006",
    projectId: 6,
    location: "Ada George, Port Harcourt",
    phase: "Finishing Stage",
    owner: "Ngozi Obi",
    start: "2026-05-01",
    end: "2026-09-30",
    status: "In Progress",
    critical: true,
    milestoneType: "Construction",
    dependsOn: "Substructure complete",
  },
  {
    id: "M-18",
    name: "Block 1 — unit handover",
    project: "Royal Crest Apartments",
    projectCode: "DEV-006",
    projectId: 6,
    location: "Ada George, Port Harcourt",
    phase: "Handover Preparation",
    owner: "Daniel Ajayi",
    start: "2026-10-01",
    end: "2027-01-15",
    status: "Planned",
    critical: true,
    milestoneType: "Handover",
    dependsOn: "Retail wing fit-out",
  },
  {
    id: "M-19",
    name: "Tower B — shell & core handover",
    project: "Atlantic View Residences",
    projectCode: "DEV-003",
    projectId: 3,
    location: "Trans Amadi, Port Harcourt",
    phase: "Roofing Stage",
    owner: "Stephen Okoro",
    start: "2026-06-15",
    end: "2026-06-28",
    status: "Planned",
    critical: true,
    milestoneType: "Handover",
    dependsOn: "Tower B — foundation complete",
  },
  {
    id: "M-20",
    name: "Retail wing — fit-out handover",
    project: "Royal Crest Apartments",
    projectCode: "DEV-006",
    projectId: 6,
    location: "Ada George, Port Harcourt",
    phase: "Handover Preparation",
    owner: "Daniel Ajayi",
    start: "2026-06-20",
    end: "2026-07-02",
    status: "Planned",
    critical: true,
    milestoneType: "Handover",
    dependsOn: "Retail wing fit-out",
  },
];

export function countUpcomingHandovers(
  items: PortfolioMilestone[],
  withinDays = 30,
): number {
  const cutoff = moment().add(withinDays, "days");
  return items.filter(
    (m) =>
      m.milestoneType === "Handover" &&
      m.status !== "Completed" &&
      m.status !== "Cancelled" &&
      moment(m.end).isSameOrBefore(cutoff),
  ).length;
}
